<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>$(AssemblyName)</Title>
    <Version>0.1.60.24239</Version>
    <Company>Codespirals</Company>
    <NeutralLanguage>en</NeutralLanguage>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageIcon>spiral.png</PackageIcon>
    <PackageOutputPath>..\..\..\NuGet_local</PackageOutputPath>
    <PackageLicenseExpression>CC0-1.0</PackageLicenseExpression>
    <PackageTags>codespirals;modular;</PackageTags>
    <RepositoryUrl>https://github.com/Codespirals/Codespirals.Base.git</RepositoryUrl>
    <PackageProjectUrl>https://codespirals.dev</PackageProjectUrl>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'" />
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="PowerShell -ExecutionPolicy Bypass -NoProfile -File AutoUpdateVersionNumber.ps1" />
  </Target>
  <ItemGroup>
    <EmbeddedResource Remove="Resources\Images\Resources.resx" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\Images\spiral.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <EmbeddedResource Include="Resources\Images\spiral.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>