<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>$(AssemblyName)</Title>
    <Version>1.0.16.24346</Version>
    <Company>codespirals</Company>
    <NeutralLanguage>en</NeutralLanguage>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageIcon>spiral.png</PackageIcon>
    <PackageOutputPath>..\..\..\NuGet_local</PackageOutputPath>
    <PackageLicenseExpression>CC0-1.0</PackageLicenseExpression>
    <PackageTags>codespirals;modular;</PackageTags>
    <RepositoryUrl>https://github.com/Codespirals/Codespirals.Base.git</RepositoryUrl>
    <PackageProjectUrl>https://codespirals.dev</PackageProjectUrl>
    <Copyright>$(Company)</Copyright>
    <Authors>codespirals</Authors>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\Codespirals.Base.Resources\Images\spiral.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Codespirals.Base.Abstractions" Version="1.0.41.25006" />
    <PackageReference Include="Codespirals.Base.Impl" Version="0.0.5.24294" />
    <PackageReference Include="Codespirals.Base.Resources" Version="1.0.15.24294" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="PowerShell -ExecutionPolicy Bypass -NoProfile -File AutoUpdateVersionNumber.ps1" />
  </Target>
</Project>