<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Copyright>$(Company)</Copyright>
    <PackageProjectUrl>https://codespirals.dev/</PackageProjectUrl>
    <Title>$(AssemblyName)</Title>
    <Company>codespirals</Company>
    <Authors>codespirals</Authors>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.233.26061</Version>
    <PackageIcon>logo.png</PackageIcon>
    <PackageTags>codespirals;modular;abstractions;</PackageTags>
    <PackageOutputPath>$(OneDrive)\NuGet</PackageOutputPath>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
    <PackageLicenseExpression>CC0-1.0</PackageLicenseExpression>
    <RootNamespace>Codespirals.Base</RootNamespace>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Codespirals/Codespirals.Base.git</RepositoryUrl>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
  <PropertyGroup>
    <Today>$([System.DateTime]::Now.ToString('yyyy.MM.dd'))</Today>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Interfaces\Selectalbes\**" />
    <EmbeddedResource Remove="Interfaces\Selectalbes\**" />
    <None Remove="Interfaces\Selectalbes\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\Images\logo.png" />
    <None Remove="Resources\README.md" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Images\icon.png">
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <Pack>True</Pack>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Images\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.11" />
    <Resource Include="Resources\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\Validation\" />
  </ItemGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="PowerShell -ExecutionPolicy Bypass -NoProfile -File AutoUpdateVersionNumber.ps1" />
  </Target>
</Project>