<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Copyright>$(codespirals)</Copyright>
    <PackageProjectUrl>https://codespirals.dev/</PackageProjectUrl>
    <Title>$(AssemblyName)</Title>
    <Authors>codespirals</Authors>
    <Company>codespirals</Company>
    <Version>1.0.15.24294</Version>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageIcon>spiral.png</PackageIcon>
    <PackageTags>codespirals;modular;resources;</PackageTags>
    <PackageOutputPath>..\..\..\NuGet_local</PackageOutputPath>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Images\spiral.png">
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>True</Pack>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Codespirals.Base.Abstractions" Version="1.0.23.24293">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="Codespirals.Base.Impl" Version="0.0.4.24293" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.8" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Images\spiral.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="PowerShell -ExecutionPolicy Bypass -NoProfile -File AutoUpdateVersionNumber.ps1" />
  </Target>
</Project>