<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>$(AssemblyName)</Title>
    <Version>0.1.22.25055</Version>
    <Authors>$(Company)</Authors>
    <Company>codespirals</Company>
    <PackageIcon>logo.png</PackageIcon>
    <RepositoryUrl>https://github.com/Codespirals/Codespirals.Users.git</RepositoryUrl>
    <PackageTags>codespirals,modular,database,EFCore</PackageTags>
    <PackageOutputPath>../../../NuGet_local</PackageOutputPath>
    <PackageLicenseExpression>CC0-1.0</PackageLicenseExpression>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <RootNamespace>Codespirals.Base</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\Codespirals.Base.Shared\Resources\Images\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Codespirals.Base.Shared" Version="1.0.60.25042" />
    <PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Resources\ComponentText.Designer.cs">
      <DependentUpon>ComponentText.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources\ComponentText.resx">
      <LastGenOutput>ComponentText.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Using Include="Codespirals.Base" />
    <Using Include="Codespirals.Base.Resources" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Scripts\" />
  </ItemGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="PowerShell -ExecutionPolicy Bypass -NoProfile -File AutoUpdateVersionNumber.ps1" />
  </Target>
</Project>